### ISSUE TITLE
dataset BaseDataset

### ISSUE THREAD

**Issue by jdivis** [emreaksan/deepwriting#19]
Hello, when I run the following command:

`python visualize_hw.py -D ./data/deepwriting_validation.npz -O ./data_images -S 1 5 20`

I received the error:

`ModuleNotFoundError: No module named 'dataset'`

I tried: 

`pip install dataset`

But then get the error:

```
Traceback (most recent call last):
  File "C:\ci\code\deepwriting\visualize_hw.py", line 164, in <module>
    from dataset_hw import HandWritingDatasetConditional as Dataset
  File "C:\ci\code\deepwriting\dataset_hw.py", line 7, in <module>
    from dataset import BaseDataset
ImportError: cannot import name 'BaseDataset' from 'dataset' (......\Python\Python310\site-packages\dataset\__init__.py)
```

I then cd'ed into source and changed the command I was running from:

`python visualize_hw.py -D ./data/deepwriting_validation.npz -O ./data_images -S 1 5 20`

to:

`python utils_visualization.py -D ./data/deepwriting_validation.npz -O ./data_images -S 1 5 20`

the command ran, but I'm not seeing that the data_images folder is created.

**Comment by jdivis** [comment]
missed adding ./source to %PythonPath%
